-- Replaces the human-security dimensions of the recommendations of A/HRC/60/8 with HRCT's reviewed
-- classification. The first assignment gave almost three dimensions to each recommendation
-- (954 links: community security in 222 of the 324 recommendations, political security in 202,
-- food security in 22 although no recommendation names food). Each recommendation was classified
-- again from its official text: a dimension is assigned only when the measure requested responds
-- to a threat that belongs to it, and each link says why.
-- Criteria: docs/human-security.md. Review: data/human-security/hrct-review-spain-upr4.json.
-- The rows below are the output of `node scripts/human-security-review.mjs --sql`.
-- Safe to run again.

alter table public.commitment_human_security
  add column if not exists reviewed_at date;

create or replace view public.hrct_public_human_security with (security_invoker = true) as
select c.public_id, d.code, d.name, d.description, chs.is_primary, chs.rationale, chs.reviewed_at
from public.commitment_human_security chs
join public.commitments c on c.id=chs.commitment_id
join public.human_security_dimensions d on d.id=chs.dimension_id
where c.publication_status='published';

create temp table human_security_review (n int, code text, is_primary boolean not null, rationale text not null, primary key (n, code));

-- (recommendation 50.n, dimension, primary, why)
insert into human_security_review values
  (1, 'economic', true, $es$La Convención protege las condiciones de trabajo, la remuneración y la seguridad social de los trabajadores migratorios y de sus familias.$es$),
  (2, 'economic', true, $es$La Convención protege las condiciones de trabajo, la remuneración y la seguridad social de los trabajadores migratorios y de sus familias.$es$),
  (3, 'economic', true, $es$La Convención protege las condiciones de trabajo, la remuneración y la seguridad social de los trabajadores migratorios y de sus familias.$es$),
  (4, 'political', true, $es$El Protocolo Facultativo abre una vía de denuncia individual por la vulneración de los derechos civiles y políticos.$es$),
  (5, 'community', true, $es$El genocidio es la destrucción de un grupo nacional, étnico, racial o religioso como tal: la amenaza extrema a la seguridad de una comunidad.$es$),
  (5, 'personal', false, $es$Se comete mediante la matanza y las lesiones graves a los miembros del grupo.$es$),
  (6, 'personal', true, $es$Las armas nucleares son una amenaza de violencia armada a gran escala contra la población civil.$es$),
  (7, 'personal', true, $es$Las armas nucleares son una amenaza de violencia armada a gran escala contra la población civil.$es$),
  (8, 'economic', true, $es$Las medidas coercitivas unilaterales restringen el comercio y las finanzas de un país y repercuten en los medios de vida de su población.$es$),
  (10, 'political', true, $es$El Defensor del Pueblo supervisa a la Administración y protege a las personas frente a sus abusos.$es$),
  (11, 'community', true, $es$El Observatorio mide el racismo y la xenofobia: la hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (12, 'personal', true, $es$El feminicidio es la forma extrema de la violencia contra las mujeres.$es$),
  (13, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (14, 'personal', true, $es$El uso de la fuerza y de las armas de fuego por agentes del Estado puede causar muertes y lesiones.$es$),
  (14, 'political', false, $es$Se aplica a las manifestaciones y a las fronteras, donde el exceso de fuerza restringe derechos y libertades.$es$),
  (15, 'political', true, $es$La manipulación de la información vicia el debate público y el ejercicio de las libertades de opinión e información.$es$),
  (16, 'technological', true, $es$La diversidad en el diseño y el uso de la inteligencia artificial reduce el riesgo de sesgos y de exclusión en los sistemas automatizados.$es$),
  (17, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (18, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (19, 'community', true, $es$Los delitos de odio se cometen contra las personas por su pertenencia a un grupo.$es$),
  (19, 'personal', false, $es$Incluyen agresiones y amenazas contra la integridad de las personas.$es$),
  (20, 'community', true, $es$El antisemitismo es hostilidad hacia una comunidad por su identidad religiosa y cultural.$es$),
  (21, 'political', true, $es$El Plan Nacional de Derechos Humanos ordena la actuación del Estado para proteger los derechos y las libertades.$es$),
  (22, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (23, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (24, 'community', true, $es$El discurso de odio señala a las personas por su pertenencia a un grupo y deteriora la convivencia entre comunidades.$es$),
  (25, 'community', true, $es$La incitación al odio señala a las personas por su pertenencia a un grupo y deteriora la convivencia entre comunidades.$es$),
  (25, 'technological', false, $es$Se refiere de forma expresa a la incitación al odio y las amenazas en Internet.$es$),
  (26, 'community', true, $es$El perfilado racial trata a las personas como sospechosas por su pertenencia a un grupo étnico.$es$),
  (26, 'political', false, $es$Es una práctica de los cuerpos de seguridad: un abuso en el ejercicio de la autoridad pública.$es$),
  (27, 'community', true, $es$El perfilado racial trata a las personas como sospechosas por su pertenencia a un grupo étnico.$es$),
  (27, 'political', false, $es$Es una práctica de los cuerpos de seguridad: un abuso en el ejercicio de la autoridad pública.$es$),
  (28, 'community', true, $es$El perfilado racial trata a las personas como sospechosas por su pertenencia a un grupo étnico.$es$),
  (28, 'political', false, $es$Es una práctica de los cuerpos de seguridad: un abuso en el ejercicio de la autoridad pública.$es$),
  (29, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (29, 'political', false, $es$Pide poner fin al perfilado racial por las fuerzas de seguridad: un abuso en el ejercicio de la autoridad pública.$es$),
  (30, 'community', true, $es$El perfilado racial trata a las personas como sospechosas por su pertenencia a un grupo étnico.$es$),
  (30, 'political', false, $es$Es una práctica de los cuerpos de seguridad: un abuso en el ejercicio de la autoridad pública.$es$),
  (31, 'community', true, $es$El discurso de odio señala a las personas por su pertenencia a un grupo y deteriora la convivencia entre comunidades.$es$),
  (31, 'political', false, $es$Pide poner fin al perfilado racial por las fuerzas de seguridad: un abuso en el ejercicio de la autoridad pública.$es$),
  (32, 'community', true, $es$Se refiere a los delitos de odio contra personas pertenecientes a minorías nacionales, étnicas, religiosas y lingüísticas.$es$),
  (32, 'personal', false, $es$Incluyen agresiones y amenazas contra la integridad de las personas.$es$),
  (32, 'technological', false, $es$Nombra de forma expresa los delitos de odio cometidos en línea.$es$),
  (33, 'community', true, $es$Los delitos de odio se cometen contra las personas por su pertenencia a un grupo.$es$),
  (33, 'personal', false, $es$Incluyen agresiones y amenazas contra la integridad de las personas.$es$),
  (34, 'community', true, $es$El discurso de odio señala a las personas por su pertenencia a un grupo y deteriora la convivencia entre comunidades.$es$),
  (34, 'technological', false, $es$Nombra de forma expresa Internet o el entorno digital, donde el odio alcanza una difusión mayor.$es$),
  (35, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (35, 'technological', false, $es$Nombra de forma expresa Internet o el entorno digital, donde el odio alcanza una difusión mayor.$es$),
  (36, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (37, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (38, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (38, 'technological', false, $es$Nombra de forma expresa Internet o el entorno digital, donde el odio alcanza una difusión mayor.$es$),
  (39, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (40, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (41, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (42, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (43, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (43, 'personal', false, $es$Nombra a las víctimas de los delitos motivados por el odio, que incluyen agresiones y amenazas.$es$),
  (44, 'community', true, $es$La discriminación y la intolerancia deterioran la convivencia entre los grupos de una sociedad.$es$),
  (45, 'economic', true, $es$El empleo y la vivienda son dos de los ámbitos en los que pide lograr la igualdad.$es$),
  (45, 'health', false, $es$Nombra de forma expresa la atención de la salud.$es$),
  (45, 'community', false, $es$Se refiere a la discriminación de las personas afrodescendientes.$es$),
  (46, 'community', true, $es$Reparar la discriminación y favorecer la participación de los grupos expuestos a la exclusión refuerza la cohesión social.$es$),
  (47, 'community', true, $es$Se dirige contra la discriminación de migrantes, minorías étnicas y afrodescendientes.$es$),
  (47, 'economic', false, $es$Pide igualdad de acceso al empleo, la educación y los servicios públicos.$es$),
  (48, 'community', true, $es$Se refiere a la discriminación estructural del pueblo gitano y de las personas afrodescendientes.$es$),
  (49, 'economic', true, $es$La discriminación de las mujeres en el empleo limita su acceso a un trabajo y a unos ingresos en igualdad.$es$),
  (50, 'community', true, $es$Se refiere a los casos de discriminación motivados por la identidad racial o religiosa de las víctimas.$es$),
  (51, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (52, 'community', true, $es$Se refiere a la discriminación de las mujeres gitanas, refugiadas y migrantes por su origen.$es$),
  (53, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (54, 'community', true, $es$La segregación escolar por origen étnico separa a los alumnos según el grupo al que pertenecen.$es$),
  (54, 'economic', false, $es$La segregación por motivos socioeconómicos reproduce la pobreza de una generación a la siguiente.$es$),
  (55, 'personal', true, $es$La tortura y los malos tratos son violencia física y psíquica contra la persona.$es$),
  (55, 'political', false, $es$Son abusos cometidos por agentes del Estado o con su consentimiento; una definición legal incompleta favorece la impunidad.$es$),
  (56, 'personal', true, $es$La tortura y los malos tratos son violencia física y psíquica contra la persona.$es$),
  (56, 'political', false, $es$Son abusos cometidos por agentes del Estado o con su consentimiento; una definición legal incompleta favorece la impunidad.$es$),
  (57, 'personal', true, $es$La tortura y los malos tratos son violencia física y psíquica contra la persona.$es$),
  (57, 'political', false, $es$Son abusos cometidos por agentes del Estado o con su consentimiento; una definición legal incompleta favorece la impunidad.$es$),
  (58, 'personal', true, $es$La tortura y los malos tratos son violencia física y psíquica contra la persona.$es$),
  (58, 'political', false, $es$Son abusos cometidos por agentes del Estado o con su consentimiento; una definición legal incompleta favorece la impunidad.$es$),
  (59, 'personal', true, $es$La tortura y los malos tratos son violencia física y psíquica contra la persona.$es$),
  (59, 'political', false, $es$Son abusos cometidos por agentes del Estado o con su consentimiento; la prescripción del delito favorece la impunidad.$es$),
  (60, 'personal', true, $es$La tortura y los malos tratos son violencia física y psíquica contra la persona.$es$),
  (60, 'political', false, $es$La detención en régimen de incomunicación suspende garantías de la persona detenida frente a los agentes del Estado.$es$),
  (61, 'personal', true, $es$La tortura y los malos tratos son violencia física y psíquica contra la persona.$es$),
  (61, 'political', false, $es$Son abusos cometidos por agentes del Estado o con su consentimiento; su persecución efectiva es una garantía frente al abuso institucional.$es$),
  (62, 'personal', true, $es$La devolución expone a las personas al riesgo de persecución, tortura o muerte en el país de destino.$es$),
  (62, 'political', false, $es$Las devoluciones colectivas privan de un examen individual y de garantías frente a la actuación del Estado.$es$),
  (63, 'political', true, $es$La incomunicación suspende garantías básicas de la persona detenida, como la asistencia de un abogado de su elección.$es$),
  (63, 'personal', false, $es$El aislamiento daña la integridad física y psíquica, en particular la de los menores.$es$),
  (64, 'personal', true, $es$El uso excesivo de la fuerza es violencia física ejercida por agentes del Estado.$es$),
  (64, 'political', false, $es$Su investigación imparcial es una garantía frente al abuso institucional y la impunidad.$es$),
  (65, 'economic', true, $es$Las medidas coercitivas unilaterales restringen el comercio y las finanzas de un país y repercuten en los medios de vida de su población.$es$),
  (66, 'personal', true, $es$El hacinamiento expone a las personas privadas de libertad a la violencia y a condiciones de reclusión degradantes.$es$),
  (67, 'political', true, $es$La transparencia y la rendición de cuentas de las instituciones son garantías frente al abuso institucional.$es$),
  (68, 'political', true, $es$La independencia judicial es la garantía última de los derechos frente al poder.$es$),
  (69, 'political', true, $es$Una justicia eficaz y accesible es la garantía de los derechos y las libertades.$es$),
  (70, 'political', true, $es$La independencia judicial es la garantía última de los derechos frente al poder.$es$),
  (71, 'political', true, $es$La verdad, la justicia y la reparación responden a violaciones graves de derechos cometidas mediante la represión política.$es$),
  (72, 'political', true, $es$La verdad, la justicia y la reparación responden a violaciones graves de derechos cometidas mediante la represión política.$es$),
  (73, 'political', true, $es$La verdad, la justicia y la reparación responden a violaciones graves de derechos cometidas mediante la represión política.$es$),
  (74, 'technological', true, $es$Un marco ético y respetuoso de los derechos limita los riesgos que la inteligencia artificial plantea para las personas.$es$),
  (75, 'technological', true, $es$Se refiere a los riesgos del uso de la inteligencia artificial y de otras nuevas tecnologías.$es$),
  (75, 'political', false, $es$Nombra la libertad de expresión, la libertad de reunión y el derecho a la privacidad.$es$),
  (76, 'technological', true, $es$Los entornos digitales exponen a niños, niñas y adolescentes a riesgos específicos para su seguridad y sus derechos.$es$),
  (77, 'technological', true, $es$Los derechos digitales y la protección frente a la violencia en línea determinan la seguridad de las personas en el entorno digital.$es$),
  (77, 'personal', false, $es$Pide proteger de la violencia a las mujeres, los niños y otros grupos vulnerables.$es$),
  (78, 'political', true, $es$Se refiere a la criminalización y el encarcelamiento de opositores, defensores de derechos humanos y manifestantes: la represión política que esta dimensión excluye.$es$),
  (79, 'political', true, $es$La Ley de Protección de la Seguridad Ciudadana regula el ejercicio de las libertades de expresión y de reunión y las sanciones que pueden limitarlo.$es$),
  (80, 'political', true, $es$La Ley de Protección de la Seguridad Ciudadana regula el ejercicio de las libertades de expresión y de reunión y las sanciones que pueden limitarlo.$es$),
  (81, 'political', true, $es$La Ley de Protección de la Seguridad Ciudadana regula el ejercicio de las libertades de expresión y de reunión y las sanciones que pueden limitarlo.$es$),
  (82, 'political', true, $es$Las libertades de expresión, reunión y asociación son el núcleo de las libertades civiles.$es$),
  (83, 'political', true, $es$Las libertades de expresión, reunión y asociación son el núcleo de las libertades civiles.$es$),
  (84, 'political', true, $es$Las libertades de expresión, reunión y asociación son el núcleo de las libertades civiles.$es$),
  (85, 'community', true, $es$Los delitos de odio se cometen contra las personas por su pertenencia a un grupo.$es$),
  (85, 'personal', false, $es$Incluyen agresiones y amenazas contra la integridad de las personas.$es$),
  (86, 'community', true, $es$El discurso de odio señala a las personas por su pertenencia a un grupo y deteriora la convivencia entre comunidades.$es$),
  (86, 'technological', false, $es$Nombra de forma expresa Internet o el entorno digital, donde el odio alcanza una difusión mayor.$es$),
  (87, 'political', true, $es$El espionaje de miembros de la sociedad civil, legisladores y juristas es vigilancia del Estado sobre la vida política y vulnera la privacidad.$es$),
  (87, 'technological', false, $es$Se ejerce mediante programas espía que intervienen dispositivos y comunicaciones.$es$),
  (88, 'personal', true, $es$El matrimonio infantil y forzado somete a niñas y mujeres a coacción y a violencia.$es$),
  (88, 'community', false, $es$Es una práctica impuesta a la víctima desde su entorno familiar o comunitario.$es$),
  (89, 'personal', true, $es$El matrimonio infantil y forzado somete a niñas y mujeres a coacción y a violencia.$es$),
  (89, 'community', false, $es$Es una práctica impuesta a la víctima desde su entorno familiar o comunitario.$es$),
  (90, 'personal', true, $es$El matrimonio infantil y forzado somete a niñas y mujeres a coacción y a violencia.$es$),
  (90, 'community', false, $es$Es una práctica impuesta a la víctima desde su entorno familiar o comunitario.$es$),
  (91, 'economic', true, $es$Las políticas de apoyo a las familias sostienen sus medios de vida y la crianza de los hijos.$es$),
  (92, 'economic', true, $es$Las políticas de apoyo a las familias sostienen sus medios de vida y la crianza de los hijos.$es$),
  (93, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (94, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (95, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (95, 'economic', false, $es$El trabajo forzoso es una forma extrema de explotación económica.$es$),
  (96, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (97, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (98, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (99, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (100, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (101, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (102, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (103, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (104, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (105, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (106, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (107, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (108, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (109, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (110, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (110, 'economic', false, $es$El trabajo forzoso es una forma extrema de explotación económica.$es$),
  (111, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (112, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (113, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (114, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (115, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (116, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (117, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (118, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (119, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (119, 'economic', false, $es$El trabajo forzoso es una forma extrema de explotación económica.$es$),
  (120, 'personal', true, $es$La trata somete a las personas a captación, coacción y explotación: una amenaza directa a su libertad y su integridad.$es$),
  (121, 'economic', true, $es$El desempleo juvenil es una amenaza directa a la seguridad de los medios de vida.$es$),
  (122, 'economic', true, $es$El desempleo juvenil es una amenaza directa a la seguridad de los medios de vida.$es$),
  (123, 'economic', true, $es$El desempleo y la desigualdad salarial amenazan la seguridad de los medios de vida.$es$),
  (124, 'economic', true, $es$La igualdad de trato en el trabajo protege el acceso al empleo y a los ingresos.$es$),
  (124, 'health', false, $es$Nombra de forma expresa la igualdad de trato en la salud.$es$),
  (125, 'economic', true, $es$La seguridad social es la red pública de protección frente a la pérdida de ingresos.$es$),
  (126, 'economic', true, $es$Una renta mínima garantizada es la última protección frente a la pobreza.$es$),
  (127, 'economic', true, $es$La seguridad social es la red pública de protección frente a la pérdida de ingresos.$es$),
  (128, 'economic', true, $es$La seguridad social es la red pública de protección frente a la pérdida de ingresos.$es$),
  (129, 'economic', true, $es$La pobreza infantil es privación económica en la etapa de mayor vulnerabilidad de la vida.$es$),
  (130, 'economic', true, $es$El empleo juvenil, la vivienda asequible y el acceso a los servicios esenciales son condiciones básicas de la seguridad económica.$es$),
  (131, 'economic', true, $es$Carecer de una vivienda adecuada y asequible es una de las formas más graves de inseguridad económica.$es$),
  (132, 'economic', true, $es$Carecer de una vivienda adecuada y asequible es una de las formas más graves de inseguridad económica.$es$),
  (133, 'economic', true, $es$Carecer de una vivienda adecuada y asequible es una de las formas más graves de inseguridad económica.$es$),
  (134, 'economic', true, $es$Carecer de una vivienda adecuada y asequible es una de las formas más graves de inseguridad económica.$es$),
  (135, 'economic', true, $es$Carecer de una vivienda adecuada y asequible es una de las formas más graves de inseguridad económica.$es$),
  (136, 'economic', true, $es$Carecer de una vivienda adecuada y asequible es una de las formas más graves de inseguridad económica.$es$),
  (137, 'economic', true, $es$Carecer de una vivienda adecuada y asequible es una de las formas más graves de inseguridad económica.$es$),
  (138, 'economic', true, $es$Carecer de una vivienda adecuada y asequible es una de las formas más graves de inseguridad económica.$es$),
  (139, 'economic', true, $es$Carecer de una vivienda adecuada y asequible es una de las formas más graves de inseguridad económica.$es$),
  (140, 'economic', true, $es$El apoyo a las personas en situación de pobreza y su acceso a la vivienda responden a la privación económica.$es$),
  (140, 'health', false, $es$Nombra de forma expresa el acceso de los grupos vulnerables a la atención médica.$es$),
  (141, 'economic', true, $es$El Objetivo de Desarrollo Sostenible 1 es poner fin a la pobreza.$es$),
  (142, 'economic', true, $es$La pobreza infantil es privación económica en la etapa de mayor vulnerabilidad de la vida.$es$),
  (143, 'economic', true, $es$La pobreza infantil es privación económica en la etapa de mayor vulnerabilidad de la vida.$es$),
  (144, 'economic', true, $es$Reducir las disparidades económicas reduce la exposición a la pobreza y a la exclusión.$es$),
  (145, 'health', true, $es$Los servicios de salud sexual y reproductiva forman parte del acceso efectivo a la protección de la salud.$es$),
  (146, 'health', true, $es$Los servicios de salud sexual y reproductiva forman parte del acceso efectivo a la protección de la salud.$es$),
  (147, 'health', true, $es$Los servicios de salud sexual y reproductiva forman parte del acceso efectivo a la protección de la salud.$es$),
  (148, 'health', true, $es$Los servicios de salud sexual y reproductiva forman parte del acceso efectivo a la protección de la salud.$es$),
  (149, 'health', true, $es$La educación sexual integral previene los embarazos no deseados y las infecciones de transmisión sexual.$es$),
  (150, 'health', true, $es$La penalización del aborto aleja a las mujeres de la atención sanitaria y favorece las prácticas inseguras.$es$),
  (151, 'health', true, $es$La educación sexual integral previene los embarazos no deseados y las infecciones de transmisión sexual.$es$),
  (152, 'health', true, $es$La cobertura sanitaria universal es la garantía básica de acceso a la protección de la salud.$es$),
  (153, 'health', true, $es$La cobertura sanitaria universal es la garantía básica de acceso a la protección de la salud.$es$),
  (154, 'health', true, $es$La cobertura sanitaria universal es la garantía básica de acceso a la protección de la salud.$es$),
  (155, 'health', true, $es$La cobertura sanitaria universal es la garantía básica de acceso a la protección de la salud.$es$),
  (156, 'health', true, $es$La atención a la salud mental forma parte del acceso a la protección de la salud.$es$),
  (157, 'health', true, $es$La atención a la salud mental forma parte del acceso a la protección de la salud.$es$),
  (158, 'health', true, $es$El consumo de sustancias adictivas es una amenaza para la salud, en especial la de los jóvenes.$es$),
  (159, 'health', true, $es$Pide garantizar el derecho a la salud a todas las personas, incluidas las migrantes y las refugiadas.$es$),
  (159, 'economic', false, $es$La educación y los servicios sociales protegen frente a la pobreza y la exclusión.$es$),
  (160, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (161, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (162, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (163, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (164, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (164, 'community', false, $es$Se refiere a la desigualdad educativa que afecta a las minorías.$es$),
  (165, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (166, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (167, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (168, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (169, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (170, 'community', true, $es$La lengua es un elemento central de la identidad cultural de una comunidad.$es$),
  (171, 'environmental', true, $es$El cambio climático es una amenaza ambiental para la vida y el bienestar de las personas.$es$),
  (172, 'environmental', true, $es$El cambio climático es una amenaza ambiental que obliga a las personas a desplazarse.$es$),
  (173, 'environmental', true, $es$El cambio climático es una amenaza ambiental para la vida y el bienestar de las personas.$es$),
  (174, 'environmental', true, $es$El cambio climático es una amenaza ambiental para la vida y el bienestar de las personas.$es$),
  (174, 'economic', false, $es$Pide proteger de los efectos del cambio climático a las personas en situación de pobreza mediante la protección social.$es$),
  (175, 'environmental', true, $es$La financiación climática permite a los países en desarrollo protegerse de las amenazas ambientales.$es$),
  (176, 'environmental', true, $es$Las catástrofes y los riesgos climáticos son amenazas ambientales directas para la vida.$es$),
  (177, 'environmental', true, $es$El cambio climático es una amenaza ambiental para la vida y el bienestar de las personas.$es$),
  (178, 'environmental', true, $es$El cambio climático es una amenaza ambiental para la vida y el bienestar de las personas.$es$),
  (179, 'environmental', true, $es$Se refiere a la elaboración de las políticas frente a las amenazas ambientales.$es$),
  (180, 'environmental', true, $es$El derecho a un medio ambiente limpio, saludable y sostenible es la respuesta jurídica a las amenazas ambientales.$es$),
  (181, 'economic', true, $es$Reducir la pobreza y la desigualdad es el objeto mismo de la seguridad económica.$es$),
  (182, 'economic', true, $es$Las medidas coercitivas unilaterales restringen el comercio y las finanzas de un país y repercuten en los medios de vida de su población.$es$),
  (184, 'personal', true, $es$Los programas a los que se refiere previenen la violencia de género y atienden a sus víctimas.$es$),
  (187, 'community', true, $es$El genocidio es la destrucción de un grupo nacional, étnico, racial o religioso como tal: la amenaza extrema a la seguridad de una comunidad.$es$),
  (187, 'personal', false, $es$Se comete mediante la matanza y las lesiones graves a los miembros del grupo.$es$),
  (190, 'political', true, $es$La presencia de las mujeres en los puestos de decisión forma parte del derecho a participar en la vida pública.$es$),
  (191, 'political', true, $es$La presencia de las mujeres en los puestos de decisión forma parte del derecho a participar en la vida pública.$es$),
  (192, 'economic', true, $es$Se refiere al trabajo, la propiedad y la protección social de las mujeres del medio rural.$es$),
  (193, 'economic', true, $es$Se refiere al trabajo, la propiedad y la protección social de las mujeres del medio rural.$es$),
  (194, 'economic', true, $es$Se refiere al trabajo, la propiedad y la protección social de las mujeres del medio rural.$es$),
  (195, 'economic', true, $es$Se refiere al trabajo, la propiedad y la protección social de las mujeres del medio rural.$es$),
  (196, 'economic', true, $es$La escasa presencia de mujeres en las disciplinas científicas y técnicas limita su acceso a empleos cualificados.$es$),
  (197, 'economic', true, $es$La escasa presencia de mujeres en las disciplinas científicas y técnicas limita su acceso a empleos cualificados.$es$),
  (198, 'technological', true, $es$La formación digital condiciona el acceso en igualdad al entorno digital y su uso seguro.$es$),
  (199, 'technological', true, $es$La formación digital condiciona el acceso en igualdad al entorno digital y su uso seguro.$es$),
  (202, 'economic', true, $es$Se refiere al acceso de las mujeres al empleo público y a su promoción profesional.$es$),
  (203, 'economic', true, $es$La participación de las mujeres en la educación condiciona su acceso al empleo y a unos ingresos propios.$es$),
  (204, 'economic', true, $es$La discriminación de las mujeres en el empleo limita su acceso a un trabajo y a unos ingresos en igualdad.$es$),
  (205, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (205, 'community', false, $es$Se refiere a la desigualdad educativa que afecta al pueblo gitano.$es$),
  (206, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (206, 'economic', false, $es$Nombra de forma expresa la igualdad de género en el empleo.$es$),
  (207, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (208, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (209, 'personal', true, $es$La violencia sexual es una amenaza directa a la integridad de las personas.$es$),
  (210, 'personal', true, $es$La violencia sexual es una amenaza directa a la integridad de las personas.$es$),
  (211, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (212, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (213, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (214, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (215, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (216, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (217, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (218, 'personal', true, $es$El feminicidio es la forma extrema de la violencia contra las mujeres.$es$),
  (219, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (219, 'technological', false, $es$Nombra de forma expresa los abusos y la violencia que se ejercen por medios digitales.$es$),
  (220, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (221, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (222, 'personal', true, $es$El feminicidio es la forma extrema de la violencia contra las mujeres.$es$),
  (223, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (224, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (225, 'technological', true, $es$Su objeto es el entorno digital: la ciberviolencia, la regulación de las plataformas y los sesgos sexistas de la inteligencia artificial.$es$),
  (225, 'personal', false, $es$La ciberviolencia es una forma de violencia contra las mujeres y las niñas.$es$),
  (226, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (227, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (227, 'economic', false, $es$Pide reforzar la protección social de las personas que viven en la pobreza.$es$),
  (228, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (229, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (230, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (231, 'personal', true, $es$El feminicidio es la forma extrema de la violencia contra las mujeres.$es$),
  (232, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (233, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (233, 'technological', false, $es$Nombra de forma expresa los abusos y la violencia que se ejercen por medios digitales.$es$),
  (234, 'personal', true, $es$El feminicidio es la forma extrema de la violencia contra las mujeres.$es$),
  (235, 'personal', true, $es$El matrimonio forzado y la mutilación genital femenina son violencia contra mujeres y niñas.$es$),
  (235, 'community', false, $es$Son prácticas impuestas a la víctima desde su entorno familiar o comunitario.$es$),
  (236, 'personal', true, $es$El matrimonio forzado y la mutilación genital femenina son violencia contra mujeres y niñas.$es$),
  (236, 'community', false, $es$Son prácticas impuestas a la víctima desde su entorno familiar o comunitario.$es$),
  (237, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (238, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (239, 'personal', true, $es$La violencia de género es violencia física, psíquica y sexual contra las mujeres.$es$),
  (240, 'economic', true, $es$La Garantía Infantil Europea se dirige a los niños en riesgo de pobreza o de exclusión social.$es$),
  (241, 'economic', true, $es$La pobreza infantil es privación económica en la etapa de mayor vulnerabilidad de la vida.$es$),
  (242, 'economic', true, $es$La pobreza infantil es privación económica en la etapa de mayor vulnerabilidad de la vida.$es$),
  (243, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (243, 'health', false, $es$Nombra de forma expresa el acceso de los niños migrantes a la sanidad.$es$),
  (244, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (244, 'community', false, $es$Se refiere a la desigualdad educativa que afecta al pueblo gitano.$es$),
  (245, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (246, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (247, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (247, 'community', false, $es$Se refiere a la desigualdad educativa que afecta a las minorías.$es$),
  (248, 'technological', true, $es$Los entornos digitales exponen a niños, niñas y adolescentes a riesgos específicos para su seguridad y sus derechos.$es$),
  (249, 'technological', true, $es$Los entornos digitales exponen a niños, niñas y adolescentes a riesgos específicos para su seguridad y sus derechos.$es$),
  (249, 'personal', false, $es$Nombra de forma expresa la violencia y la explotación de niños y adolescentes.$es$),
  (250, 'economic', true, $es$La educación básica es la primera protección frente a la pobreza y la exclusión laboral; el abandono y el acceso desigual la debilitan.$es$),
  (251, 'personal', true, $es$Los niños que migran solos carecen de la protección de una familia y están expuestos al desamparo, los abusos y la explotación.$es$),
  (251, 'political', false, $es$Las evaluaciones de la edad y la asistencia jurídica son garantías de procedimiento frente a la Administración.$es$),
  (252, 'personal', true, $es$Los niños que migran solos carecen de la protección de una familia y están expuestos al desamparo, los abusos y la explotación.$es$),
  (253, 'personal', true, $es$Los niños que migran solos carecen de la protección de una familia y están expuestos al desamparo, los abusos y la explotación.$es$),
  (254, 'personal', true, $es$Los niños que migran solos carecen de la protección de una familia y están expuestos al desamparo, los abusos y la explotación.$es$),
  (255, 'political', true, $es$La determinación de la edad decide si una persona recibe la protección debida a un niño: exige garantías de procedimiento.$es$),
  (256, 'personal', true, $es$Los niños que migran solos carecen de la protección de una familia y están expuestos al desamparo, los abusos y la explotación.$es$),
  (257, 'personal', true, $es$Pide proteger a niños y adolescentes de todas las formas de violencia.$es$),
  (259, 'technological', true, $es$Los entornos digitales exponen a niños, niñas y adolescentes a riesgos específicos para su seguridad y sus derechos.$es$),
  (260, 'technological', true, $es$Los entornos digitales exponen a niños, niñas y adolescentes a riesgos específicos para su seguridad y sus derechos.$es$),
  (261, 'technological', true, $es$Conocer los efectos y los riesgos de la inteligencia artificial, en especial para los menores, permite un uso más seguro de la tecnología.$es$),
  (262, 'personal', true, $es$Los niños que migran solos carecen de la protección de una familia y están expuestos al desamparo, los abusos y la explotación.$es$),
  (263, 'personal', true, $es$Los exámenes genitales invasivos atentan contra la integridad física y la dignidad del niño.$es$),
  (263, 'political', false, $es$La determinación de la edad decide si una persona recibe la protección debida a un niño: exige garantías de procedimiento.$es$),
  (264, 'health', true, $es$Los cuidados y la atención domiciliaria protegen la salud y la autonomía de las personas mayores y dependientes.$es$),
  (265, 'health', true, $es$Los cuidados y la atención domiciliaria protegen la salud y la autonomía de las personas mayores y dependientes.$es$),
  (266, 'health', true, $es$Los cuidados y la atención domiciliaria protegen la salud y la autonomía de las personas mayores y dependientes.$es$),
  (268, 'economic', true, $es$Las barreras en el empleo, la educación y la vivienda privan a las personas con discapacidad de unos medios de vida autónomos.$es$),
  (269, 'economic', true, $es$Las barreras en el empleo, la educación y la vivienda privan a las personas con discapacidad de unos medios de vida autónomos.$es$),
  (270, 'economic', true, $es$Las barreras en el empleo, la educación y la vivienda privan a las personas con discapacidad de unos medios de vida autónomos.$es$),
  (271, 'economic', true, $es$Las barreras en el empleo, la educación y la vivienda privan a las personas con discapacidad de unos medios de vida autónomos.$es$),
  (271, 'health', false, $es$Nombra de forma expresa el acceso a la atención sanitaria.$es$),
  (272, 'economic', true, $es$Las barreras en el empleo, la educación y la vivienda privan a las personas con discapacidad de unos medios de vida autónomos.$es$),
  (273, 'economic', true, $es$Las barreras en el empleo, la educación y la vivienda privan a las personas con discapacidad de unos medios de vida autónomos.$es$),
  (274, 'health', true, $es$La rehabilitación es un servicio de salud del que depende la autonomía de las personas con discapacidad.$es$),
  (275, 'economic', true, $es$La segregación escolar del alumnado con discapacidad limita su formación y, con ella, su autonomía económica.$es$),
  (276, 'economic', true, $es$La segregación escolar del alumnado con discapacidad limita su formación y, con ella, su autonomía económica.$es$),
  (277, 'economic', true, $es$La segregación escolar del alumnado con discapacidad limita su formación y, con ella, su autonomía económica.$es$),
  (278, 'economic', true, $es$Las barreras en el empleo, la educación y la vivienda privan a las personas con discapacidad de unos medios de vida autónomos.$es$),
  (279, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (280, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (281, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (281, 'technological', false, $es$Nombra de forma expresa Internet o el entorno digital, donde el odio alcanza una difusión mayor.$es$),
  (282, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (283, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (284, 'community', true, $es$El racismo y la xenofobia son hostilidad hacia las personas por su pertenencia a un grupo étnico o nacional.$es$),
  (284, 'technological', false, $es$Nombra de forma expresa Internet o el entorno digital, donde el odio alcanza una difusión mayor.$es$),
  (285, 'community', true, $es$Los delitos de odio se cometen contra las personas por su pertenencia a un grupo.$es$),
  (285, 'personal', false, $es$Incluyen agresiones y amenazas contra la integridad de las personas.$es$),
  (286, 'community', true, $es$Se dirige contra la islamofobia y la incitación al odio hacia las minorías étnicas y religiosas.$es$),
  (287, 'community', true, $es$El perfilado racial trata a las personas como sospechosas por su pertenencia a un grupo étnico.$es$),
  (287, 'political', false, $es$Es una práctica de los cuerpos de seguridad: un abuso en el ejercicio de la autoridad pública.$es$),
  (288, 'community', true, $es$El perfilado racial trata a las personas como sospechosas por su pertenencia a un grupo étnico.$es$),
  (288, 'political', false, $es$Es una práctica de los cuerpos de seguridad: un abuso en el ejercicio de la autoridad pública.$es$),
  (289, 'community', true, $es$Los delitos de odio se cometen contra las personas por su pertenencia a un grupo.$es$),
  (289, 'political', false, $es$Pide reducir el perfilado racial por las fuerzas del orden: un abuso en el ejercicio de la autoridad pública.$es$),
  (289, 'personal', false, $es$Los delitos de odio incluyen agresiones y amenazas contra la integridad de las personas.$es$),
  (290, 'community', true, $es$Los delitos de odio se cometen contra las personas por su pertenencia a un grupo.$es$),
  (290, 'personal', false, $es$Incluyen agresiones y amenazas contra la integridad de las personas.$es$),
  (291, 'community', true, $es$Protege el ejercicio de la identidad religiosa de las comunidades minoritarias.$es$),
  (292, 'community', true, $es$La lengua es un elemento central de la identidad de las minorías lingüísticas.$es$),
  (294, 'health', true, $es$De la formación del personal sanitario depende el acceso efectivo a la salud de las personas LGTBI.$es$),
  (295, 'economic', true, $es$El acceso al empleo sin discriminación es la base de unos medios de vida seguros.$es$),
  (296, 'community', true, $es$Se dirige contra la discriminación de las personas inmigrantes por su origen.$es$),
  (297, 'economic', true, $es$Las condiciones de trabajo de los trabajadores migrantes determinan la seguridad de sus medios de vida.$es$),
  (297, 'health', false, $es$Nombra de forma expresa el acceso a servicios sanitarios adecuados.$es$),
  (298, 'health', true, $es$Se refiere al acceso de las personas migrantes a la atención sanitaria.$es$),
  (299, 'economic', true, $es$Las condiciones de trabajo de los trabajadores migrantes determinan la seguridad de sus medios de vida.$es$),
  (299, 'health', false, $es$Nombra de forma expresa el acceso a una atención sanitaria adecuada.$es$),
  (300, 'economic', true, $es$El acceso a los servicios sociales básicos cubre necesidades esenciales de quienes carecen de otros medios.$es$),
  (301, 'political', true, $es$Las políticas de migración y asilo se aplican mediante el control de fronteras, la detención y la expulsión: el respeto de los derechos es aquí una garantía frente a la actuación del Estado.$es$),
  (302, 'political', true, $es$Las políticas de migración y asilo se aplican mediante el control de fronteras, la detención y la expulsión: el respeto de los derechos es aquí una garantía frente a la actuación del Estado.$es$),
  (303, 'personal', true, $es$Prohíbe entregar a una persona a un riesgo de desaparición forzada, tortura o malos tratos.$es$),
  (303, 'political', false, $es$Es una garantía frente a las decisiones de expulsión o extradición del Estado.$es$),
  (304, 'personal', true, $es$Los niños que migran solos carecen de la protección de una familia y están expuestos al desamparo, los abusos y la explotación.$es$),
  (305, 'political', true, $es$Las políticas de migración y asilo se aplican mediante el control de fronteras, la detención y la expulsión: el respeto de los derechos es aquí una garantía frente a la actuación del Estado.$es$),
  (306, 'political', true, $es$Las políticas de migración y asilo se aplican mediante el control de fronteras, la detención y la expulsión: el respeto de los derechos es aquí una garantía frente a la actuación del Estado.$es$),
  (307, 'personal', true, $es$La trata es una amenaza directa a la libertad y la integridad de las personas.$es$),
  (307, 'political', false, $es$Las políticas de migración y asilo se aplican mediante el control de fronteras, la detención y la expulsión: el respeto de los derechos es aquí una garantía frente a la actuación del Estado.$es$),
  (308, 'political', true, $es$El registro da a las personas en situación irregular reconocimiento ante la Administración y acceso a la protección de sus derechos.$es$),
  (309, 'economic', true, $es$Las condiciones de acogida cubren las necesidades básicas de alojamiento y manutención de quienes carecen de medios propios.$es$),
  (310, 'political', true, $es$Las políticas de migración y asilo se aplican mediante el control de fronteras, la detención y la expulsión: el respeto de los derechos es aquí una garantía frente a la actuación del Estado.$es$),
  (311, 'economic', true, $es$El acceso a los servicios sociales básicos cubre necesidades esenciales de quienes carecen de otros medios.$es$),
  (312, 'political', true, $es$Las políticas de migración y asilo se aplican mediante el control de fronteras, la detención y la expulsión: el respeto de los derechos es aquí una garantía frente a la actuación del Estado.$es$),
  (313, 'political', true, $es$Las políticas de migración y asilo se aplican mediante el control de fronteras, la detención y la expulsión: el respeto de los derechos es aquí una garantía frente a la actuación del Estado.$es$),
  (314, 'community', true, $es$La estigmatización desde el poder político señala a grupos enteros de la población y deteriora la cohesión social.$es$),
  (315, 'political', true, $es$El asilo protege frente a la persecución; el acceso al procedimiento y sus garantías dependen de la actuación del Estado.$es$),
  (316, 'political', true, $es$El asilo protege frente a la persecución; el acceso al procedimiento y sus garantías dependen de la actuación del Estado.$es$),
  (317, 'economic', true, $es$El acceso a los servicios sociales básicos cubre necesidades esenciales de quienes carecen de otros medios.$es$),
  (318, 'community', true, $es$Se dirige contra la discriminación de inmigrantes y solicitantes de asilo por su origen.$es$),
  (318, 'personal', false, $es$Nombra de forma expresa los abusos y los malos tratos.$es$),
  (319, 'economic', true, $es$Las condiciones de acogida cubren las necesidades básicas de alojamiento y manutención de quienes carecen de medios propios.$es$),
  (319, 'health', false, $es$Nombra de forma expresa la igualdad de acceso a la salud.$es$),
  (320, 'economic', true, $es$Las condiciones de acogida cubren las necesidades básicas de alojamiento y manutención de quienes carecen de medios propios.$es$),
  (321, 'political', true, $es$El asilo protege frente a la persecución; el acceso al procedimiento y sus garantías dependen de la actuación del Estado.$es$),
  (322, 'political', true, $es$El asilo protege frente a la persecución; el acceso al procedimiento y sus garantías dependen de la actuación del Estado.$es$),
  (323, 'political', true, $es$El reasentamiento da protección frente a la persecución a personas refugiadas; su alcance depende de un compromiso del Estado.$es$),
  (324, 'personal', true, $es$Los niños que migran solos carecen de la protección de una familia y están expuestos al desamparo, los abusos y la explotación.$es$);

-- Links of the catalogue that the review does not keep.
delete from public.commitment_human_security h
using public.commitments c, public.human_security_dimensions d
where c.id = h.commitment_id
  and d.id = h.dimension_id
  and c.public_id like 'ESP-UPR4-050.%'
  and not exists (select 1 from human_security_review r where c.public_id = 'ESP-UPR4-050.' || r.n and r.code = d.code);

insert into public.commitment_human_security (commitment_id, dimension_id, is_primary, rationale, reviewed_at)
select c.id, d.id, r.is_primary, r.rationale, date '2026-10-06'
from human_security_review r
  join public.commitments c on c.public_id = 'ESP-UPR4-050.' || r.n
  join public.human_security_dimensions d on d.code = r.code
on conflict (commitment_id, dimension_id) do update set is_primary = excluded.is_primary, rationale = excluded.rationale, reviewed_at = excluded.reviewed_at;

drop table human_security_review;
