-- Replaces the UHRI tagging of the recommendations of A/HRC/60/8 with HRCT's own classification
-- by Sustainable Development Goal and target. The UHRI tagging links by keyword in places (human
-- trafficking with target 15.7, on trafficking in protected species) and uses few targets, so each
-- recommendation was classified again from its official text, with the UHRI as a reference.
-- Criteria: docs/sdg.md. Review: data/sdg/hrct-review-spain-upr4.json, with a rationale per link.
-- The rows below are the output of `node scripts/sdg-review.mjs --sql`.
-- Safe to run again.

alter table public.commitment_sdgs
  add column if not exists rationale text,
  add column if not exists reviewed_at date;

create or replace view public.hrct_public_sdgs with (security_invoker = true) as
select c.public_id, s.goal, s.targets, s.source, s.source_published_at, s.rationale, s.reviewed_at
from public.commitment_sdgs s
join public.commitments c on c.id=s.commitment_id
where c.publication_status='published';

create temp table sdg_review (n int, goal smallint, targets text[], rationale text not null, primary key (n, goal));

-- (recommendation 50.n, goal, targets of that goal, why)
insert into sdg_review values
  (1, 8, '{8.8}', $es$La Convención reconoce los derechos laborales de los trabajadores migratorios y de sus familias.$es$),
  (1, 10, '{10.7}', $es$Ratificarla asienta la política migratoria en los derechos de las personas migrantes.$es$),
  (2, 8, '{8.8}', $es$La Convención reconoce los derechos laborales de los trabajadores migratorios y de sus familias.$es$),
  (2, 10, '{10.7}', $es$Ratificarla asienta la política migratoria en los derechos de las personas migrantes.$es$),
  (3, 8, '{8.8}', $es$La Convención reconoce los derechos laborales de los trabajadores migratorios y de sus familias.$es$),
  (3, 10, '{10.7}', $es$Ratificarla asienta la política migratoria en los derechos de las personas migrantes.$es$),
  (4, 16, '{16.3}', $es$El Protocolo permite presentar denuncias individuales ante el Comité de Derechos Humanos: una vía más de acceso a la justicia.$es$),
  (5, 16, '{16.1,16.3}', $es$Prevenir y sancionar el genocidio responde a la reducción de la violencia y al estado de derecho en el plano internacional.$es$),
  (6, 16, '{}', $es$El desarme nuclear pertenece al ámbito de la paz, pero ninguna meta de la Agenda 2030 lo recoge.$es$),
  (7, 16, '{}', $es$El desarme nuclear pertenece al ámbito de la paz, pero ninguna meta de la Agenda 2030 lo recoge.$es$),
  (9, 17, '{17.9}', $es$Pide más asistencia técnica: apoyo a la creación de capacidad en otros países.$es$),
  (10, 16, '{16.6,16.a}', $es$El Defensor del Pueblo es la institución nacional de derechos humanos; la existencia de instituciones independientes de este tipo es el indicador de la meta 16.a.$es$),
  (11, 10, '{10.3}', $es$El Observatorio es un instrumento de la lucha contra la discriminación racial.$es$),
  (11, 16, '{16.6}', $es$Dotarlo de medios es reforzar una institución pública para que sea eficaz.$es$),
  (12, 5, '{5.2}', $es$Mejorar los datos sobre feminicidios sirve para prevenir la violencia de género.$es$),
  (12, 16, '{16.1}', $es$Se refiere a las muertes violentas y al papel de las armas de fuego.$es$),
  (13, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (13, 16, '{16.3,16.b}', $es$Pide una estrategia nacional y que se investigue, persiga y sancione la incitación al odio.$es$),
  (14, 10, '{10.7}', $es$El uso de la fuerza en las fronteras afecta a la seguridad de las personas migrantes.$es$),
  (14, 16, '{16.1,16.10}', $es$Regular el uso de la fuerza y de las armas reduce la violencia; en las manifestaciones protege además la libertad de reunión.$es$),
  (15, 16, '{16.10}', $es$La resistencia a la desinformación protege el acceso público a la información.$es$),
  (16, 10, '{10.2}', $es$La diversidad en la inteligencia artificial busca la inclusión de todas las personas, sin sesgos por sexo, origen u otra condición.$es$),
  (17, 10, '{10.2,10.3}', $es$El Marco Estratégico combina inclusión y lucha contra la discriminación racial.$es$),
  (17, 16, '{16.6,16.b}', $es$Es una política no discriminatoria, y se piden mecanismos de seguimiento y rendición de cuentas.$es$),
  (18, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (18, 16, '{16.b}', $es$Pide adoptar un plan nacional: una política no discriminatoria.$es$),
  (19, 10, '{10.3}', $es$Los delitos de odio son la expresión más grave de la discriminación.$es$),
  (19, 16, '{16.1,16.b}', $es$Son una forma de violencia, y se pide un plan de acción para combatirlos.$es$),
  (20, 10, '{10.3}', $es$El antisemitismo es una forma de discriminación por motivos de religión u origen.$es$),
  (20, 16, '{16.b}', $es$Se refiere a la aplicación de un plan nacional: políticas no discriminatorias.$es$),
  (21, 16, '{16.6,16.7}', $es$Un plan nacional de derechos humanos compromete a las instituciones y permite exigirles cuentas; se pide además la participación de la sociedad civil.$es$),
  (22, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (23, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (24, 10, '{10.3}', $es$El discurso de odio es una manifestación de discriminación.$es$),
  (25, 10, '{10.3}', $es$La incitación al odio es una manifestación de discriminación.$es$),
  (25, 16, '{16.1}', $es$Las amenazas son una forma de violencia.$es$),
  (26, 10, '{10.3}', $es$El perfilado racial es una práctica discriminatoria de los cuerpos de seguridad.$es$),
  (26, 16, '{16.b}', $es$Erradicarlo requiere normas y políticas policiales no discriminatorias.$es$),
  (27, 10, '{10.3}', $es$El perfilado racial es una práctica discriminatoria de los cuerpos de seguridad.$es$),
  (27, 16, '{16.b}', $es$Pide disposiciones legales que prohíban los controles de identidad por perfil étnico.$es$),
  (28, 10, '{10.3}', $es$El perfilado racial es una práctica discriminatoria de los cuerpos de seguridad.$es$),
  (28, 16, '{16.b}', $es$Erradicarlo requiere normas y políticas policiales no discriminatorias.$es$),
  (29, 10, '{10.3}', $es$El perfilado racial es una práctica discriminatoria de los cuerpos de seguridad.$es$),
  (29, 16, '{16.b}', $es$Erradicarlo requiere normas y políticas policiales no discriminatorias.$es$),
  (30, 10, '{10.3}', $es$El perfilado racial es una práctica discriminatoria de los cuerpos de seguridad.$es$),
  (30, 16, '{16.b}', $es$Erradicarlo requiere normas y políticas policiales no discriminatorias.$es$),
  (31, 10, '{10.3}', $es$Discriminación, discurso de odio y perfilado racial son prácticas discriminatorias.$es$),
  (31, 16, '{16.b}', $es$Erradicarlo requiere normas y políticas policiales no discriminatorias.$es$),
  (32, 10, '{10.3}', $es$Los delitos de odio contra las minorías son la expresión más grave de la discriminación.$es$),
  (32, 16, '{16.1}', $es$Los delitos de odio son una forma de violencia.$es$),
  (33, 10, '{10.3}', $es$Discurso y delitos de odio son manifestaciones de discriminación.$es$),
  (33, 16, '{16.1,16.b}', $es$Los delitos de odio son violencia; se pide además aplicar plenamente la legislación contra el racismo.$es$),
  (34, 10, '{10.3}', $es$El discurso de odio y la retórica racista son manifestaciones de discriminación.$es$),
  (34, 16, '{16.3}', $es$Pide perseguir y castigar a los autores.$es$),
  (35, 10, '{10.3}', $es$Una ley integral contra la discriminación en el empleo, la educación y la sanidad.$es$),
  (35, 16, '{16.b}', $es$Pide aprobar legislación antidiscriminatoria.$es$),
  (36, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (36, 16, '{16.b}', $es$Pide aprobar legislación específica contra la discriminación racial.$es$),
  (37, 4, '{4.7}', $es$Pide programas educativos sobre el racismo: educación en derechos humanos y en la diversidad.$es$),
  (37, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (37, 16, '{16.b}', $es$Pide aplicar plenamente la legislación contra el racismo y la discriminación.$es$),
  (38, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (39, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (40, 10, '{10.3}', $es$La discriminación racial y el discurso de odio vulneran la igualdad de oportunidades.$es$),
  (41, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (42, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (43, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (43, 16, '{16.3,16.6,16.b}', $es$Pide legislación, rendición de cuentas institucional y acceso a la justicia para las víctimas de delitos de odio.$es$),
  (44, 10, '{10.3}', $es$Erradicar la discriminación y la intolerancia es el objeto de la meta 10.3.$es$),
  (45, 3, '{3.8}', $es$Igualdad en el acceso a la atención de la salud.$es$),
  (45, 8, '{8.5}', $es$Igualdad en el empleo; la meta menciona expresamente a las personas con discapacidad.$es$),
  (45, 10, '{10.3}', $es$Combatir la discriminación de las personas con discapacidad y afrodescendientes.$es$),
  (45, 11, '{11.1}', $es$Igualdad en el acceso a la vivienda.$es$),
  (46, 10, '{10.2,10.3}', $es$Pide remediar la discriminación y fomentar la participación social de las personas con discapacidad y migrantes.$es$),
  (46, 16, '{16.3}', $es$Un sistema público y accesible de reparación es una vía de acceso a la justicia.$es$),
  (47, 1, '{1.4}', $es$Igualdad de acceso a los servicios públicos.$es$),
  (47, 4, '{4.5}', $es$Igualdad de acceso a la educación.$es$),
  (47, 8, '{8.5}', $es$Igualdad de acceso al empleo.$es$),
  (47, 10, '{10.3}', $es$Combatir la discriminación de migrantes, minorías étnicas y afrodescendientes.$es$),
  (48, 10, '{10.2,10.3}', $es$La discriminación estructural de la población gitana y afrodescendiente exige eliminar prácticas discriminatorias y promover su inclusión.$es$),
  (49, 5, '{5.1,5.c}', $es$Evaluar y aplicar las leyes de igualdad para acabar con la discriminación de las mujeres en el trabajo.$es$),
  (49, 8, '{8.5}', $es$Trabajo decente e igualdad de remuneración para las mujeres.$es$),
  (50, 10, '{10.3}', $es$Discriminación por identidad racial o religiosa.$es$),
  (50, 16, '{16.b}', $es$Pide mejorar la aplicación de la legislación contra la discriminación.$es$),
  (51, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (51, 16, '{16.b}', $es$Pide una revisión nacional y un plan estratégico: una política no discriminatoria.$es$),
  (52, 5, '{5.1}', $es$Discriminación que sufren las mujeres gitanas, refugiadas y migrantes.$es$),
  (52, 10, '{10.3}', $es$Discriminación múltiple por origen étnico y situación migratoria.$es$),
  (53, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (53, 16, '{16.6}', $es$Pide mecanismos de rendición de cuentas.$es$),
  (54, 4, '{4.1,4.5}', $es$La segregación escolar impide una enseñanza equitativa y la igualdad de acceso de los alumnos vulnerables.$es$),
  (54, 10, '{10.3}', $es$Segregar por origen étnico o socioeconómico es una práctica discriminatoria.$es$),
  (55, 16, '{16.1,16.3}', $es$La tortura es violencia ejercida por agentes del Estado; tipificarla y perseguirla conforme a la Convención es además una exigencia del estado de derecho.$es$),
  (56, 16, '{16.1,16.3}', $es$La tortura es violencia ejercida por agentes del Estado; tipificarla y perseguirla conforme a la Convención es además una exigencia del estado de derecho.$es$),
  (57, 16, '{16.1,16.3}', $es$La tortura es violencia ejercida por agentes del Estado; tipificarla y perseguirla conforme a la Convención es además una exigencia del estado de derecho.$es$),
  (58, 16, '{16.1,16.3}', $es$La tortura es violencia ejercida por agentes del Estado; tipificarla y perseguirla conforme a la Convención es además una exigencia del estado de derecho.$es$),
  (59, 16, '{16.1,16.3}', $es$Que la tortura no prescriba evita la impunidad de una forma de violencia ejercida por agentes del Estado.$es$),
  (60, 16, '{16.1,16.3}', $es$La legislación sobre tortura y detención incomunicada debe ofrecer las garantías propias del estado de derecho.$es$),
  (61, 16, '{16.1,16.3}', $es$Reforzar la persecución de la tortura y los malos tratos reduce la violencia institucional y la impunidad.$es$),
  (62, 10, '{10.7}', $es$El principio de no devolución y la prohibición de las devoluciones colectivas son condiciones de una migración segura.$es$),
  (62, 16, '{16.3}', $es$Exige un examen individual con garantías: estado de derecho y acceso a la justicia.$es$),
  (63, 16, '{16.2,16.3}', $es$La incomunicación y el aislamiento suprimen garantías básicas de la detención; aplicados a menores, son una forma de maltrato.$es$),
  (64, 16, '{16.1,16.3,16.6}', $es$Investigar con imparcialidad el uso excesivo de la fuerza reduce la violencia y hace que las fuerzas del orden rindan cuentas.$es$),
  (66, 16, '{16.3}', $es$El hacinamiento penitenciario depende del funcionamiento del sistema de justicia; el indicador de esta meta mide la población reclusa sin condena.$es$),
  (67, 16, '{16.6}', $es$Transparencia y rendición de cuentas de las instituciones públicas: el texto de la meta 16.6.$es$),
  (68, 16, '{16.3,16.6}', $es$La independencia judicial es condición del estado de derecho y de unas instituciones que rindan cuentas.$es$),
  (69, 16, '{16.3,16.6}', $es$Pide una justicia eficaz y con recursos suficientes, y mejor acceso a ella.$es$),
  (70, 16, '{16.3,16.6}', $es$La capacidad y la independencia del poder judicial sostienen el estado de derecho.$es$),
  (71, 16, '{16.3}', $es$La justicia transicional da acceso a la justicia a las víctimas de la dictadura.$es$),
  (72, 16, '{16.3}', $es$Verdad, justicia, reparación y garantías de no repetición para las víctimas de la Guerra Civil y la dictadura.$es$),
  (73, 16, '{16.3}', $es$Difundir los principios de verdad, justicia y reparación afianza el estado de derecho.$es$),
  (74, 16, '{16.10}', $es$Un marco ético para la inteligencia artificial protege las libertades fundamentales frente a sus usos lesivos.$es$),
  (75, 10, '{10.3}', $es$Pide que la tecnología no se use para discriminar.$es$),
  (75, 16, '{16.10}', $es$Protege la libertad de expresión, la de reunión y la privacidad frente a las nuevas tecnologías.$es$),
  (76, 16, '{16.2}', $es$Proteger a los menores en línea frente al abuso, la explotación y la violencia.$es$),
  (77, 5, '{5.2}', $es$Protección de las mujeres frente a la violencia en línea.$es$),
  (77, 16, '{16.2,16.10}', $es$Protección de los niños frente a la violencia en línea y promoción de los derechos digitales.$es$),
  (78, 16, '{16.3,16.10}', $es$Se refiere a la persecución penal de opositores, defensores de derechos humanos y manifestantes: libertades fundamentales y garantías judiciales.$es$),
  (79, 16, '{16.3,16.10}', $es$La Ley de Seguridad Ciudadana afecta a las libertades de expresión y reunión; se pide ajustarla a las normas internacionales.$es$),
  (80, 16, '{16.10}', $es$Las libertades de expresión, reunión y asociación son libertades fundamentales, que la meta 16.10 pide proteger.$es$),
  (81, 16, '{16.10}', $es$Las libertades de expresión, reunión y asociación son libertades fundamentales, que la meta 16.10 pide proteger.$es$),
  (82, 16, '{16.10}', $es$Libertad de opinión y de expresión de la sociedad civil y los periodistas.$es$),
  (83, 16, '{16.10}', $es$Las libertades de expresión, reunión y asociación son libertades fundamentales, que la meta 16.10 pide proteger.$es$),
  (84, 10, '{10.2}', $es$Participación política de las minorías.$es$),
  (84, 16, '{16.10}', $es$Las libertades de expresión, reunión y asociación son libertades fundamentales, que la meta 16.10 pide proteger.$es$),
  (85, 10, '{10.3}', $es$Los delitos de odio son la expresión más grave de la discriminación.$es$),
  (85, 16, '{16.1}', $es$Los delitos de odio son una forma de violencia.$es$),
  (86, 10, '{10.3}', $es$El discurso de odio en línea es una manifestación de discriminación.$es$),
  (87, 16, '{16.10}', $es$El espionaje a la sociedad civil, legisladores y juristas vulnera la privacidad y las libertades fundamentales.$es$),
  (88, 5, '{5.3}', $es$El matrimonio infantil y forzado es una de las prácticas nocivas que la meta 5.3 pide eliminar.$es$),
  (89, 5, '{5.3}', $es$Fijar sin excepciones la edad mínima de 18 años combate el matrimonio infantil, práctica nociva de la meta 5.3.$es$),
  (90, 5, '{5.3}', $es$El matrimonio forzado es una de las prácticas nocivas que la meta 5.3 pide eliminar.$es$),
  (91, 1, '{1.3}', $es$El apoyo a las familias se presta a través de los sistemas de protección social.$es$),
  (92, 1, '{1.3}', $es$Las políticas de apoyo a la familia y la infancia forman parte de la protección social.$es$),
  (93, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (94, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (95, 5, '{5.2}', $es$Destaca la protección de las mujeres y las niñas y la explotación sexual.$es$),
  (95, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (96, 5, '{5.2}', $es$Pide reforzar la protección de las mujeres víctimas.$es$),
  (96, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (96, 16, '{16.2,16.3}', $es$Menciona a los niños víctimas y pide simplificar el acceso a la justicia.$es$),
  (97, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (98, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (99, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (100, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (101, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (102, 5, '{5.2}', $es$Se refiere a la trata de mujeres.$es$),
  (102, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (102, 10, '{10.7}', $es$Las víctimas son mujeres migrantes: migración segura.$es$),
  (103, 5, '{5.2}', $es$Busca proteger mejor a las mujeres víctimas de la trata.$es$),
  (103, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (103, 10, '{10.7}', $es$Las víctimas son mujeres migrantes: migración segura.$es$),
  (103, 16, '{16.3}', $es$Pide simplificar su acceso a la justicia.$es$),
  (104, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (105, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (105, 16, '{16.2}', $es$Se refiere expresamente a los niños víctimas de la trata.$es$),
  (106, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (106, 16, '{16.3}', $es$Pide reforzar el enjuiciamiento de los casos de trata.$es$),
  (107, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (108, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (108, 16, '{16.4}', $es$Pide una estrategia nacional contra la delincuencia organizada.$es$),
  (109, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (109, 16, '{16.3}', $es$Pide garantizar a las víctimas servicios jurídicos.$es$),
  (110, 5, '{5.2}', $es$Se refiere en particular a las mujeres víctimas de la trata.$es$),
  (110, 8, '{8.7}', $es$Trata de personas, en particular con fines de trabajo forzoso.$es$),
  (110, 10, '{10.7}', $es$Pide detectar la trata en las fronteras y proteger a las mujeres migrantes.$es$),
  (110, 16, '{16.3}', $es$Pide garantizar el acceso de las víctimas a la justicia.$es$),
  (111, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (112, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (113, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (114, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (115, 5, '{5.2}', $es$Incluye expresamente la trata de mujeres y niñas.$es$),
  (115, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (116, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (116, 10, '{10.7}', $es$Las víctimas solicitan protección internacional: migración segura.$es$),
  (117, 5, '{5.2}', $es$Destaca la protección de las mujeres y las niñas.$es$),
  (117, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (117, 16, '{16.2}', $es$Se refiere expresamente a los niños víctimas de la trata.$es$),
  (118, 5, '{5.2}', $es$Destaca la protección de las mujeres víctimas.$es$),
  (118, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (118, 16, '{16.2}', $es$Se refiere expresamente a los niños víctimas de la trata.$es$),
  (119, 8, '{8.7}', $es$La trata con fines de trabajo forzoso es el núcleo de la meta 8.7.$es$),
  (120, 5, '{5.2}', $es$Se refiere en particular a las mujeres.$es$),
  (120, 8, '{8.7}', $es$La meta 8.7 pide erradicar la trata de personas, junto al trabajo forzoso y las formas contemporáneas de esclavitud.$es$),
  (120, 10, '{10.7}', $es$Las víctimas son mujeres migrantes: migración segura.$es$),
  (121, 8, '{8.5,8.6}', $es$Empleo de los jóvenes, en particular de las mujeres jóvenes.$es$),
  (122, 4, '{4.4}', $es$Programas de formación que den a los jóvenes las competencias para acceder al empleo.$es$),
  (122, 8, '{8.6}', $es$Reducir el número de jóvenes sin empleo ni formación.$es$),
  (123, 8, '{8.5,8.6}', $es$Reducir el desempleo, en especial el juvenil, y reforzar la igualdad salarial.$es$),
  (123, 10, '{10.3}', $es$Medidas contra la discriminación en el empleo.$es$),
  (124, 3, '{3.8}', $es$Igualdad de trato en la salud.$es$),
  (124, 4, '{4.5}', $es$Igualdad de trato en la educación.$es$),
  (124, 8, '{8.5}', $es$Igualdad de trato en el trabajo.$es$),
  (124, 10, '{10.3}', $es$La igualdad de trato es la igualdad de oportunidades de la meta 10.3.$es$),
  (125, 1, '{1.3}', $es$Seguridad social para las personas y los grupos en situación de vulnerabilidad.$es$),
  (126, 1, '{1.2,1.3}', $es$Una garantía de ingresos mínimos es un nivel mínimo de protección social frente a la pobreza.$es$),
  (127, 1, '{1.3}', $es$Reforzar el sistema de seguridad social.$es$),
  (127, 8, '{8.5}', $es$La reforma del mercado laboral persigue el empleo pleno y el trabajo decente.$es$),
  (128, 1, '{1.3}', $es$Mejorar los sistemas de protección social y simplificar el acceso a la asistencia social.$es$),
  (129, 1, '{1.2,1.3}', $es$Protección social frente a la pobreza infantil, incluida una prestación universal por hijo.$es$),
  (129, 4, '{4.2}', $es$Gratuidad de la educación de la primera infancia para los niños en riesgo de pobreza.$es$),
  (130, 1, '{1.4}', $es$Reducir las disparidades en el acceso a los servicios esenciales.$es$),
  (130, 8, '{8.5,8.6}', $es$Empleo juvenil.$es$),
  (130, 11, '{11.1}', $es$Accesibilidad de la vivienda.$es$),
  (131, 11, '{11.1}', $es$El acceso de todas las personas a una vivienda adecuada, segura y asequible es el contenido de la meta 11.1.$es$),
  (132, 11, '{11.1}', $es$El acceso de todas las personas a una vivienda adecuada, segura y asequible es el contenido de la meta 11.1.$es$),
  (133, 11, '{11.1}', $es$El acceso de todas las personas a una vivienda adecuada, segura y asequible es el contenido de la meta 11.1.$es$),
  (134, 11, '{11.1}', $es$El acceso de todas las personas a una vivienda adecuada, segura y asequible es el contenido de la meta 11.1.$es$),
  (135, 11, '{11.1}', $es$El acceso de todas las personas a una vivienda adecuada, segura y asequible es el contenido de la meta 11.1.$es$),
  (136, 11, '{11.1}', $es$El acceso de todas las personas a una vivienda adecuada, segura y asequible es el contenido de la meta 11.1.$es$),
  (137, 11, '{11.1}', $es$El acceso de todas las personas a una vivienda adecuada, segura y asequible es el contenido de la meta 11.1.$es$),
  (138, 11, '{11.1}', $es$El acceso de todas las personas a una vivienda adecuada, segura y asequible es el contenido de la meta 11.1.$es$),
  (139, 11, '{11.1}', $es$El acceso de todas las personas a una vivienda adecuada, segura y asequible es el contenido de la meta 11.1.$es$),
  (140, 1, '{1.2}', $es$Apoyo a las personas que viven en la pobreza.$es$),
  (140, 3, '{3.8}', $es$Acceso de los grupos vulnerables a la atención médica.$es$),
  (140, 11, '{11.1}', $es$Acceso de los grupos vulnerables a la vivienda.$es$),
  (141, 1, '{}', $es$La recomendación se refiere al Objetivo 1 en su conjunto.$es$),
  (142, 1, '{1.2,1.3}', $es$Una prestación universal por hijo es una medida de protección social contra la pobreza infantil.$es$),
  (143, 1, '{1.2}', $es$Prevenir y combatir la pobreza infantil.$es$),
  (143, 10, '{10.2}', $es$Combatir la exclusión social de la infancia.$es$),
  (144, 10, '{10.2,10.4}', $es$Reducir las disparidades económicas mediante políticas sociales y promover la integración social.$es$),
  (145, 3, '{3.7}', $es$Acceso universal a los servicios de salud sexual y reproductiva, incluidas la información y la educación.$es$),
  (145, 5, '{5.6}', $es$Salud sexual y reproductiva y derechos reproductivos.$es$),
  (146, 3, '{3.7}', $es$Acceso universal a los servicios de salud sexual y reproductiva, incluidas la información y la educación.$es$),
  (146, 5, '{5.6}', $es$Salud sexual y reproductiva y derechos reproductivos.$es$),
  (147, 3, '{3.7}', $es$Acceso universal a los servicios de salud sexual y reproductiva, incluidas la información y la educación.$es$),
  (147, 5, '{5.6}', $es$Salud sexual y reproductiva y derechos reproductivos.$es$),
  (148, 3, '{3.7}', $es$Acceso universal a los servicios de salud sexual y reproductiva, incluidas la información y la educación.$es$),
  (148, 5, '{5.6}', $es$Salud sexual y reproductiva y derechos reproductivos.$es$),
  (149, 3, '{3.7}', $es$Acceso universal a los servicios de salud sexual y reproductiva, incluidas la información y la educación.$es$),
  (149, 4, '{4.7}', $es$La educación sexual integral forma parte de la educación en derechos humanos e igualdad de género.$es$),
  (149, 5, '{5.6}', $es$Salud sexual y reproductiva y derechos reproductivos.$es$),
  (150, 5, '{5.6}', $es$Despenalizar el aborto afecta a los derechos reproductivos de las mujeres.$es$),
  (151, 3, '{3.7}', $es$Acceso universal a los servicios de salud sexual y reproductiva, incluidas la información y la educación.$es$),
  (151, 4, '{4.7}', $es$La educación sexual integral forma parte de la educación en derechos humanos e igualdad de género.$es$),
  (151, 5, '{5.6}', $es$Salud sexual y reproductiva y derechos reproductivos.$es$),
  (152, 3, '{3.8}', $es$Cobertura sanitaria universal y acceso a servicios de salud de calidad para todos.$es$),
  (153, 3, '{3.8}', $es$Cobertura sanitaria universal y acceso a servicios de salud de calidad para todos.$es$),
  (154, 3, '{3.8}', $es$Cobertura sanitaria universal y acceso a servicios de salud de calidad para todos.$es$),
  (155, 3, '{3.8}', $es$Cobertura sanitaria universal y acceso a servicios de salud de calidad para todos.$es$),
  (156, 3, '{3.4,3.8}', $es$Atención de salud de calidad para todos, incluida la salud mental, que promueve la meta 3.4.$es$),
  (157, 3, '{3.4,3.8}', $es$Salud mental de niños y adolescentes en la atención primaria.$es$),
  (158, 3, '{3.5}', $es$Prevención del consumo de sustancias adictivas entre los jóvenes.$es$),
  (159, 1, '{1.4}', $es$Acceso a los servicios sociales.$es$),
  (159, 3, '{3.8}', $es$Derecho a la salud sin discriminación.$es$),
  (159, 4, '{4.5}', $es$Derecho a la educación sin discriminación.$es$),
  (159, 10, '{10.3}', $es$Igualdad de las personas migrantes y refugiadas en el acceso a los derechos sociales.$es$),
  (160, 4, '{4.1,4.5}', $es$Acceso y matriculación de los niños de zonas rurales y de grupos desfavorecidos.$es$),
  (161, 4, '{4.1,4.5}', $es$Políticas frente al fracaso y el abandono escolar de los grupos más afectados.$es$),
  (162, 4, '{4.1,4.5}', $es$Acceso equitativo a la educación de los niños desfavorecidos.$es$),
  (163, 4, '{4.a}', $es$Pide más infraestructuras educativas en las zonas rurales.$es$),
  (164, 4, '{4.5}', $es$Igualdad de acceso a la educación para los grupos en situación de vulnerabilidad.$es$),
  (165, 4, '{4.5,4.a}', $es$Eliminar los obstáculos a la educación de las personas con discapacidad, migrantes y solicitantes de asilo.$es$),
  (166, 4, '{4.1,4.5}', $es$Educación inclusiva, gratuita y de calidad para todos los niños.$es$),
  (167, 4, '{4.1,4.5}', $es$Derecho a la educación de todos los niños, sin discriminación.$es$),
  (168, 4, '{4.1,4.5}', $es$Abandono escolar prematuro, repetición de curso y segregación escolar.$es$),
  (169, 4, '{4.1}', $es$Financiación suficiente de una educación gratuita e inclusiva.$es$),
  (170, 4, '{4.7}', $es$La enseñanza de las lenguas regionales fomenta la valoración de la diversidad cultural.$es$),
  (170, 11, '{11.4}', $es$Las lenguas forman parte del patrimonio cultural que la meta 11.4 pide salvaguardar.$es$),
  (171, 13, '{13.1,13.2}', $es$Estrategias de adaptación al cambio climático y de mitigación.$es$),
  (172, 10, '{10.7}', $es$Pide tener en cuenta la movilidad humana provocada por el clima.$es$),
  (172, 13, '{13.2}', $es$Políticas de adaptación y mitigación con objetivos e indicadores.$es$),
  (173, 13, '{13.1,13.2}', $es$Aplicación del Plan Nacional de Adaptación al Cambio Climático.$es$),
  (174, 1, '{1.3,1.5}', $es$Protección social que reduzca la exposición de las personas pobres a los efectos del clima.$es$),
  (174, 13, '{13.2}', $es$Una ley integral sobre el cambio climático.$es$),
  (175, 13, '{13.a}', $es$Financiación climática para los países en desarrollo: el compromiso de la meta 13.a.$es$),
  (176, 11, '{11.b}', $es$Reducción del riesgo de desastres.$es$),
  (176, 13, '{13.1,13.3}', $es$Resiliencia frente a los riesgos climáticos y sistemas de alerta temprana.$es$),
  (177, 13, '{13.2}', $es$Plan nacional de reducción de la huella de carbono.$es$),
  (178, 13, '{13.2}', $es$Enfoque de derechos humanos y de género en las contribuciones determinadas a nivel nacional y objetivo de 1,5 ºC.$es$),
  (179, 16, '{16.7}', $es$Participación de niños y jóvenes en la adopción de decisiones.$es$),
  (181, 1, '{1.2}', $es$Reducir la pobreza.$es$),
  (181, 10, '{}', $es$Reducir la desigualdad es el Objetivo 10 en su conjunto.$es$),
  (183, 12, '{12.6}', $es$Un instrumento vinculante sobre empresas y derechos humanos persigue prácticas empresariales responsables.$es$),
  (184, 5, '{5.2}', $es$Los programas compartidos son de prevención de la violencia de género y atención a las víctimas.$es$),
  (184, 17, '{17.9}', $es$Cooperación Sur-Sur y triangular para la creación de capacidad.$es$),
  (185, 17, '{}', $es$Cooperación internacional con los países en desarrollo: el Objetivo 17 en su conjunto.$es$),
  (186, 17, '{17.6}', $es$Intercambio de conocimientos y cooperación regional.$es$),
  (187, 16, '{16.1,16.3}', $es$Prevenir el genocidio responde a la reducción de la violencia y al estado de derecho en el plano internacional.$es$),
  (188, 5, '{5.1}', $es$Igualdad de género y no discriminación en todos los ámbitos.$es$),
  (189, 5, '{5.1,5.c}', $es$Enfoque interseccional en las normas, planes y programas de igualdad.$es$),
  (190, 5, '{5.5}', $es$Participación de las mujeres en el liderazgo y la adopción de decisiones.$es$),
  (191, 5, '{5.5}', $es$Representación igualitaria de las mujeres en los sectores público y privado.$es$),
  (192, 5, '{5.1,5.a}', $es$Derechos de las mujeres rurales.$es$),
  (192, 8, '{8.8}', $es$Derechos laborales de las trabajadoras del sector agrícola.$es$),
  (193, 1, '{1.3}', $es$Acceso de las mujeres rurales a la seguridad social.$es$),
  (193, 5, '{5.1,5.a}', $es$Igualdad de derechos de las mujeres rurales a la propiedad y a los recursos económicos.$es$),
  (194, 5, '{5.1,5.a}', $es$Igualdad de las mujeres rurales.$es$),
  (194, 8, '{8.5}', $es$Igualdad de las mujeres en el lugar de trabajo.$es$),
  (195, 5, '{5.a,5.c}', $es$Una estrategia de igualdad para las mujeres rurales.$es$),
  (196, 4, '{4.3,4.5}', $es$Acceso de las mujeres a los estudios científicos y técnicos.$es$),
  (196, 5, '{5.1}', $es$Su baja presencia en esas carreras responde a estereotipos y discriminación.$es$),
  (197, 4, '{4.3,4.5}', $es$Participación de las mujeres en la formación profesional y en las disciplinas científicas y técnicas.$es$),
  (197, 5, '{5.1}', $es$Su baja presencia en esos ámbitos responde a estereotipos y discriminación.$es$),
  (198, 4, '{4.4}', $es$Competencias digitales de la población.$es$),
  (198, 5, '{5.b}', $es$Igualdad de acceso de las mujeres y las niñas a la tecnología.$es$),
  (199, 4, '{4.4}', $es$Alfabetización y competencias digitales.$es$),
  (199, 5, '{5.b}', $es$Uso de la tecnología para el empoderamiento de las mujeres y las niñas.$es$),
  (200, 5, '{5.c}', $es$Coordinar a las administraciones refuerza las políticas de igualdad de género en todo el territorio.$es$),
  (201, 5, '{5.c}', $es$Coordinar a las administraciones refuerza las políticas de igualdad de género en todo el territorio.$es$),
  (202, 5, '{5.5}', $es$Igualdad de oportunidades de las mujeres para acceder a puestos de decisión.$es$),
  (202, 16, '{16.7}', $es$Instituciones públicas representativas.$es$),
  (203, 4, '{4.5}', $es$Eliminar las disparidades de género en la educación.$es$),
  (203, 5, '{5.1}', $es$Igualdad de las mujeres en el ámbito educativo.$es$),
  (204, 5, '{5.1}', $es$Combatir la discriminación de las mujeres en el lugar de trabajo.$es$),
  (204, 8, '{8.5}', $es$Trabajo decente e igualdad de remuneración.$es$),
  (205, 4, '{4.5}', $es$Acceso a la educación de las mujeres y niñas gitanas, refugiadas y migrantes.$es$),
  (205, 5, '{5.1}', $es$Obstáculos específicos que afrontan por ser mujeres.$es$),
  (206, 5, '{5.1,5.2}', $es$Igualdad de género y eliminación de la violencia contra la mujer.$es$),
  (206, 8, '{8.5}', $es$Igualdad de género en el empleo.$es$),
  (207, 5, '{5.1,5.2,5.5}', $es$Violencia y discriminación contra la mujer, y participación de las mujeres en todos los ámbitos.$es$),
  (208, 5, '{5.1,5.2}', $es$Violencia y discriminación contra las mujeres y las niñas.$es$),
  (209, 5, '{5.2}', $es$Recursos para prevenir la violencia sexual y garantizar los derechos de las víctimas.$es$),
  (210, 5, '{5.2}', $es$La violencia sexual es una de las formas de violencia que la meta 5.2 pide eliminar.$es$),
  (211, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (212, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (213, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (214, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (214, 16, '{16.3}', $es$Pide garantizar a las víctimas el acceso a la justicia.$es$),
  (215, 5, '{5.2}', $es$Debida diligencia y prevención en los casos de violencia doméstica.$es$),
  (216, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (217, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (218, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (218, 16, '{16.1}', $es$Los feminicidios son muertes violentas: la meta 16.1 pide reducir la violencia y su mortalidad.$es$),
  (219, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (219, 16, '{16.3}', $es$Pide mejorar la respuesta de la fiscalía y la judicatura.$es$),
  (220, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (221, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (222, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (222, 16, '{16.1,16.2}', $es$Muertes violentas de mujeres y de niños.$es$),
  (223, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (224, 5, '{5.2}', $es$Violencia de género y trata de mujeres y niñas.$es$),
  (224, 8, '{8.7}', $es$Trata de personas.$es$),
  (225, 5, '{5.1,5.2}', $es$Ciberviolencia contra mujeres y niñas y sesgos sexistas en la inteligencia artificial.$es$),
  (226, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (227, 1, '{1.3,1.5}', $es$Protección social de las personas pobres, incluidas las afectadas por el cambio climático.$es$),
  (227, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (228, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (228, 16, '{16.3}', $es$Formación obligatoria de jueces y fuerzas de seguridad para mejorar la respuesta de la justicia.$es$),
  (229, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (230, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (231, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (231, 16, '{16.1}', $es$Los feminicidios son muertes violentas: la meta 16.1 pide reducir la violencia y su mortalidad.$es$),
  (232, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (233, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (233, 16, '{16.2}', $es$Ciberviolencia contra los niños.$es$),
  (234, 5, '{5.2}', $es$Tipificar el feminicidio refuerza la respuesta penal a la violencia contra las mujeres.$es$),
  (234, 16, '{16.1}', $es$Los feminicidios son muertes violentas: la meta 16.1 pide reducir la violencia y su mortalidad.$es$),
  (235, 5, '{5.3}', $es$El matrimonio forzado y la mutilación genital femenina son las prácticas nocivas que nombra la meta 5.3.$es$),
  (236, 5, '{5.3}', $es$El matrimonio forzado y la mutilación genital femenina son las prácticas nocivas que nombra la meta 5.3.$es$),
  (237, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (237, 16, '{16.3}', $es$Pide la persecución judicial efectiva de la violencia de género.$es$),
  (238, 5, '{5.2}', $es$La meta 5.2 pide eliminar todas las formas de violencia contra las mujeres y las niñas.$es$),
  (239, 5, '{5.1,5.2}', $es$Violencia de género y discriminación, mediante la aplicación rigurosa de las leyes.$es$),
  (240, 1, '{1.2}', $es$La Garantía Infantil Europea combate la pobreza y la exclusión de la infancia.$es$),
  (240, 16, '{16.6}', $es$Pide mecanismos de rendición de cuentas.$es$),
  (241, 1, '{1.2,1.3}', $es$Protección social de los niños y las familias, con una prestación universal por hijo.$es$),
  (242, 1, '{1.2,1.3}', $es$Protección de la infancia frente a la pobreza, en especial en zonas rurales y entre la población migrante y refugiada.$es$),
  (243, 3, '{3.8}', $es$Acceso de los niños migrantes a la sanidad.$es$),
  (243, 4, '{4.1,4.5}', $es$Acceso de los niños migrantes a la educación.$es$),
  (243, 10, '{10.7}', $es$Derechos de los niños migrantes.$es$),
  (244, 4, '{4.5,4.a}', $es$Infraestructuras educativas y acceso a la educación de la población gitana.$es$),
  (245, 4, '{4.5}', $es$Acceso a una educación inclusiva de los niños en situaciones vulnerables.$es$),
  (246, 4, '{4.1,4.5}', $es$Reducir el abandono escolar temprano de los niños en riesgo de pobreza.$es$),
  (247, 4, '{4.5}', $es$Igualdad de acceso a la educación para los grupos en situación de vulnerabilidad.$es$),
  (248, 16, '{16.2}', $es$Proteger a los niños y adolescentes en el entorno digital frente al abuso, la explotación y la violencia.$es$),
  (249, 16, '{16.2}', $es$Proteger a los niños y adolescentes en el entorno digital frente al abuso, la explotación y la violencia.$es$),
  (250, 4, '{4.1,4.5}', $es$Educación de calidad para todos los niños, sin discriminación.$es$),
  (251, 10, '{10.7}', $es$La acogida y la reubicación de los menores no acompañados forman parte de una política migratoria segura y respetuosa con los derechos.$es$),
  (251, 16, '{16.2,16.3}', $es$Protección de los menores y acceso a asistencia jurídica especializada.$es$),
  (252, 10, '{10.7}', $es$La acogida y la reubicación de los menores no acompañados forman parte de una política migratoria segura y respetuosa con los derechos.$es$),
  (252, 16, '{16.2}', $es$Los menores no acompañados deben quedar protegidos frente al maltrato y la explotación.$es$),
  (253, 10, '{10.7}', $es$La acogida y la reubicación de los menores no acompañados forman parte de una política migratoria segura y respetuosa con los derechos.$es$),
  (253, 16, '{16.2}', $es$Los menores no acompañados deben quedar protegidos frente al maltrato y la explotación.$es$),
  (254, 10, '{10.7}', $es$La acogida y la reubicación de los menores no acompañados forman parte de una política migratoria segura y respetuosa con los derechos.$es$),
  (254, 16, '{16.2}', $es$Los menores no acompañados deben quedar protegidos frente al maltrato y la explotación.$es$),
  (255, 10, '{10.7}', $es$La acogida y la reubicación de los menores no acompañados forman parte de una política migratoria segura y respetuosa con los derechos.$es$),
  (255, 16, '{16.2,16.3}', $es$Protección de los menores y garantías legales en la determinación de la edad.$es$),
  (256, 10, '{10.7}', $es$Identificación de los niños en las fronteras.$es$),
  (256, 16, '{16.2}', $es$Los menores no acompañados deben quedar protegidos frente al maltrato y la explotación.$es$),
  (257, 16, '{16.2}', $es$Protección de niños y adolescentes frente a todas las formas de violencia.$es$),
  (258, 10, '{10.2}', $es$Formulación general sobre los derechos de los niños en situaciones vulnerables: corresponde a la meta de inclusión de todas las personas, sea cual sea su edad.$es$),
  (259, 16, '{16.2}', $es$Proteger a los niños y adolescentes en el entorno digital frente al abuso, la explotación y la violencia.$es$),
  (260, 16, '{16.2}', $es$Proteger a los niños y adolescentes en el entorno digital frente al abuso, la explotación y la violencia.$es$),
  (261, 4, '{4.4}', $es$Formación en inteligencia artificial: competencias digitales.$es$),
  (261, 16, '{16.2}', $es$Riesgos de la inteligencia artificial para los menores.$es$),
  (262, 10, '{10.7}', $es$La acogida y la reubicación de los menores no acompañados forman parte de una política migratoria segura y respetuosa con los derechos.$es$),
  (262, 16, '{16.2}', $es$Los menores no acompañados deben quedar protegidos frente al maltrato y la explotación.$es$),
  (263, 10, '{10.7}', $es$Determinación de la edad e interés superior del niño en el procedimiento de asilo.$es$),
  (263, 16, '{16.2}', $es$Los exámenes genitales invasivos son un trato degradante para los menores.$es$),
  (264, 1, '{1.3}', $es$La atención domiciliaria forma parte de la protección social.$es$),
  (264, 3, '{3.8}', $es$Cuidados de larga duración dentro de la cobertura sanitaria.$es$),
  (265, 1, '{1.3}', $es$La atención comunitaria y a domicilio forma parte de la protección social.$es$),
  (265, 3, '{3.8}', $es$Cuidados de larga duración dentro de la cobertura sanitaria.$es$),
  (266, 1, '{1.3}', $es$Protección social de las personas de edad.$es$),
  (266, 10, '{10.2}', $es$Inclusión de todas las personas, sea cual sea su edad.$es$),
  (267, 10, '{10.2}', $es$Derechos de las personas con discapacidad, de edad, de los niños y de las minorías.$es$),
  (267, 13, '{}', $es$Menciona los retos del cambio climático en general, sin una medida concreta.$es$),
  (268, 4, '{4.5}', $es$Igualdad de acceso de las personas con discapacidad a la educación.$es$),
  (268, 8, '{8.5}', $es$La meta 8.5 menciona expresamente el empleo de las personas con discapacidad.$es$),
  (268, 10, '{10.2}', $es$La inclusión social, económica y política de las personas con discapacidad es el objeto de la meta 10.2.$es$),
  (268, 11, '{11.1}', $es$Acceso de las personas con discapacidad a la vivienda.$es$),
  (269, 4, '{4.5}', $es$Igualdad de acceso de las personas con discapacidad a la educación.$es$),
  (269, 8, '{8.5}', $es$La meta 8.5 menciona expresamente el empleo de las personas con discapacidad.$es$),
  (269, 10, '{10.2}', $es$La inclusión social, económica y política de las personas con discapacidad es el objeto de la meta 10.2.$es$),
  (269, 11, '{11.1}', $es$Acceso de las personas con discapacidad a la vivienda.$es$),
  (270, 4, '{4.5}', $es$Igualdad de acceso de las personas con discapacidad a la educación.$es$),
  (270, 8, '{8.5}', $es$La meta 8.5 menciona expresamente el empleo de las personas con discapacidad.$es$),
  (270, 10, '{10.2}', $es$La inclusión social, económica y política de las personas con discapacidad es el objeto de la meta 10.2.$es$),
  (270, 11, '{11.1}', $es$Acceso de las personas con discapacidad a la vivienda.$es$),
  (271, 3, '{3.8}', $es$Acceso de las personas con discapacidad a la atención sanitaria.$es$),
  (271, 4, '{4.5}', $es$Igualdad de acceso de las personas con discapacidad a la educación.$es$),
  (271, 8, '{8.5}', $es$La meta 8.5 menciona expresamente el empleo de las personas con discapacidad.$es$),
  (271, 10, '{10.2}', $es$La inclusión social, económica y política de las personas con discapacidad es el objeto de la meta 10.2.$es$),
  (271, 11, '{11.1}', $es$Acceso de las personas con discapacidad a la vivienda.$es$),
  (272, 4, '{4.5,4.a}', $es$Educación inclusiva de los alumnos con discapacidad, en centros adaptados y no segregados.$es$),
  (272, 10, '{10.2}', $es$Accesibilidad de los servicios públicos para las personas con discapacidad.$es$),
  (272, 11, '{11.1}', $es$Acceso de las personas con discapacidad a la vivienda.$es$),
  (273, 8, '{8.5}', $es$La meta 8.5 menciona expresamente el empleo de las personas con discapacidad.$es$),
  (273, 10, '{10.2}', $es$La inclusión social, económica y política de las personas con discapacidad es el objeto de la meta 10.2.$es$),
  (274, 3, '{3.8}', $es$La rehabilitación forma parte de los servicios de salud esenciales.$es$),
  (275, 4, '{4.5,4.a}', $es$Educación inclusiva de los alumnos con discapacidad, en centros adaptados y no segregados.$es$),
  (276, 4, '{4.5,4.a}', $es$Educación inclusiva de los alumnos con discapacidad, en centros adaptados y no segregados.$es$),
  (277, 4, '{4.5,4.a}', $es$Educación inclusiva de los alumnos con discapacidad, en centros adaptados y no segregados.$es$),
  (278, 8, '{8.5}', $es$La meta 8.5 menciona expresamente el empleo de las personas con discapacidad.$es$),
  (278, 10, '{10.2}', $es$La inclusión social, económica y política de las personas con discapacidad es el objeto de la meta 10.2.$es$),
  (278, 11, '{11.2}', $es$Movilidad y accesibilidad: transporte accesible para las personas con discapacidad.$es$),
  (279, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (279, 16, '{16.b}', $es$Pide adoptar un plan estratégico: una política no discriminatoria.$es$),
  (280, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (280, 16, '{16.b}', $es$Pide adoptar un plan estratégico: una política no discriminatoria.$es$),
  (281, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (281, 16, '{16.b}', $es$Pide un plan de acción estratégico: una política no discriminatoria.$es$),
  (282, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (282, 16, '{16.b}', $es$Pide adoptar y aplicar de forma efectiva un plan estratégico: una política no discriminatoria.$es$),
  (283, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (283, 16, '{16.b}', $es$Pide aprobar una ley general contra el racismo y la discriminación racial.$es$),
  (284, 10, '{10.3}', $es$Combatir el racismo y la xenofobia exige eliminar las prácticas discriminatorias y garantizar la igualdad de oportunidades.$es$),
  (285, 10, '{10.3}', $es$Discriminación racial y étnica contra los miembros de minorías.$es$),
  (285, 16, '{16.1}', $es$Los delitos de odio son una forma de violencia.$es$),
  (286, 10, '{10.3}', $es$Discriminación, islamofobia e incitación al odio contra minorías étnicas y religiosas.$es$),
  (286, 16, '{16.b}', $es$Pide medidas legislativas.$es$),
  (287, 10, '{10.3}', $es$El perfilado racial es una práctica discriminatoria de los cuerpos de seguridad.$es$),
  (287, 16, '{16.b}', $es$Pide prohibir los controles de identidad basados en el perfil racial.$es$),
  (288, 10, '{10.3}', $es$El perfilado racial es una práctica discriminatoria de los cuerpos de seguridad.$es$),
  (288, 16, '{16.b}', $es$Pide prohibir los controles de identidad basados en el perfil racial y limitar los registros corporales.$es$),
  (289, 10, '{10.3}', $es$Delitos de odio y perfilado racial.$es$),
  (289, 16, '{16.3,16.b}', $es$Persecución efectiva de los delitos de odio y prácticas policiales no discriminatorias.$es$),
  (290, 10, '{10.3}', $es$Los delitos de odio son la expresión más grave de la discriminación.$es$),
  (290, 16, '{16.3}', $es$La formación de policías y personal judicial mejora la respuesta de la justicia.$es$),
  (291, 10, '{10.2,10.3}', $es$Las minorías religiosas deben ejercer sus derechos sin discriminación.$es$),
  (292, 10, '{10.3}', $es$Discriminación por motivos de lengua.$es$),
  (292, 16, '{16.b}', $es$Pide que la legislación prohíba esa discriminación.$es$),
  (293, 10, '{10.2}', $es$Formulación general sobre los grupos vulnerables: corresponde a la meta de inclusión de todas las personas.$es$),
  (294, 3, '{3.8}', $es$Una atención sanitaria que responda a las necesidades de las personas LGTBI.$es$),
  (294, 10, '{10.3}', $es$Igualdad de trato en la atención sanitaria.$es$),
  (295, 8, '{8.5}', $es$Políticas de empleo inclusivas, en especial para las personas trans.$es$),
  (295, 10, '{10.3}', $es$Igualdad de oportunidades de las personas LGTBI.$es$),
  (296, 10, '{10.3}', $es$Discriminación contra las personas inmigrantes.$es$),
  (297, 3, '{3.8}', $es$Acceso de los trabajadores migrantes a los servicios sanitarios.$es$),
  (297, 8, '{8.8}', $es$La meta 8.8 pide proteger los derechos laborales de los trabajadores migrantes.$es$),
  (298, 3, '{3.8}', $es$Acceso de las personas migrantes a la atención sanitaria.$es$),
  (298, 10, '{10.7}', $es$Proteger los derechos de las personas migrantes, refugiadas y solicitantes de asilo forma parte de una migración segura y bien gestionada.$es$),
  (299, 3, '{3.8}', $es$Acceso de los trabajadores migrantes a la atención sanitaria.$es$),
  (299, 4, '{4.5}', $es$Acceso de los trabajadores migrantes y sus familias a la educación.$es$),
  (299, 8, '{8.8}', $es$La meta 8.8 pide proteger los derechos laborales de los trabajadores migrantes.$es$),
  (300, 10, '{10.2,10.7}', $es$Integrar a los niños inmigrantes en el sistema de protección de la infancia.$es$),
  (301, 10, '{10.7}', $es$Proteger los derechos de las personas migrantes, refugiadas y solicitantes de asilo forma parte de una migración segura y bien gestionada.$es$),
  (302, 10, '{10.7}', $es$Proteger los derechos de las personas migrantes, refugiadas y solicitantes de asilo forma parte de una migración segura y bien gestionada.$es$),
  (303, 10, '{10.7}', $es$La prohibición de devolver a quien corre riesgo de tortura o desaparición forzada es condición de una migración segura.$es$),
  (303, 16, '{16.3}', $es$Exige un examen individual con garantías: estado de derecho y acceso a la justicia.$es$),
  (304, 10, '{10.7}', $es$La acogida y la reubicación de los menores no acompañados forman parte de una política migratoria segura y respetuosa con los derechos.$es$),
  (304, 16, '{16.2}', $es$Los menores no acompañados deben quedar protegidos frente al maltrato y la explotación.$es$),
  (305, 10, '{10.7}', $es$Proteger los derechos de las personas migrantes, refugiadas y solicitantes de asilo forma parte de una migración segura y bien gestionada.$es$),
  (306, 10, '{10.7}', $es$Proteger los derechos de las personas migrantes, refugiadas y solicitantes de asilo forma parte de una migración segura y bien gestionada.$es$),
  (307, 8, '{8.7}', $es$Protección de las víctimas de la trata.$es$),
  (307, 10, '{10.7}', $es$Proteger los derechos de las personas migrantes, refugiadas y solicitantes de asilo forma parte de una migración segura y bien gestionada.$es$),
  (308, 10, '{10.7}', $es$Protección de las personas migrantes en situación irregular.$es$),
  (308, 16, '{16.9}', $es$Su registro les da acceso a una identidad jurídica reconocida.$es$),
  (309, 10, '{10.7}', $es$Condiciones adecuadas en los centros de acogida e integración.$es$),
  (310, 10, '{10.7}', $es$Proteger los derechos de las personas migrantes, refugiadas y solicitantes de asilo forma parte de una migración segura y bien gestionada.$es$),
  (310, 16, '{16.2}', $es$Los menores no acompañados deben quedar protegidos frente al maltrato y la explotación.$es$),
  (311, 1, '{1.4}', $es$Eliminar las barreras de acceso a los servicios sociales básicos.$es$),
  (311, 10, '{10.7}', $es$Proteger los derechos de las personas migrantes, refugiadas y solicitantes de asilo forma parte de una migración segura y bien gestionada.$es$),
  (312, 10, '{10.7}', $es$Proteger los derechos de las personas migrantes, refugiadas y solicitantes de asilo forma parte de una migración segura y bien gestionada.$es$),
  (312, 16, '{16.2}', $es$Los menores no acompañados deben quedar protegidos frente al maltrato y la explotación.$es$),
  (313, 10, '{10.7}', $es$Políticas de migración y asilo basadas en los derechos humanos.$es$),
  (314, 10, '{10.2,10.3}', $es$La estigmatización de las personas inmigrantes y pobres por parte de las autoridades alimenta la discriminación y la exclusión.$es$),
  (315, 10, '{10.7}', $es$Acceso rápido y seguro a la protección internacional.$es$),
  (315, 16, '{16.3}', $es$El acceso al procedimiento de asilo y sus garantías son una cuestión de estado de derecho y acceso a la justicia.$es$),
  (316, 10, '{10.7}', $es$Acceso a la protección internacional.$es$),
  (317, 1, '{1.4}', $es$Acceso de las personas refugiadas y solicitantes de asilo a los servicios esenciales.$es$),
  (317, 10, '{10.7}', $es$Proteger los derechos de las personas migrantes, refugiadas y solicitantes de asilo forma parte de una migración segura y bien gestionada.$es$),
  (318, 10, '{10.3,10.7}', $es$Discriminación contra las personas inmigrantes y solicitantes de asilo.$es$),
  (318, 16, '{16.1}', $es$Los abusos y malos tratos son una forma de violencia.$es$),
  (319, 1, '{1.4}', $es$Igualdad de acceso a los servicios básicos.$es$),
  (319, 3, '{3.8}', $es$Igualdad de acceso a la salud.$es$),
  (319, 4, '{4.5}', $es$Igualdad de acceso a la educación.$es$),
  (319, 10, '{10.7}', $es$Trato digno y condiciones humanas de acogida.$es$),
  (320, 10, '{10.7}', $es$Condiciones de acogida de los solicitantes de asilo.$es$),
  (321, 10, '{10.7}', $es$Políticas de asilo y migración conformes al derecho internacional.$es$),
  (322, 10, '{10.7}', $es$Protección de los solicitantes de asilo.$es$),
  (322, 16, '{16.3}', $es$El acceso al procedimiento de asilo y sus garantías son una cuestión de estado de derecho y acceso a la justicia.$es$),
  (323, 10, '{10.3,10.7}', $es$Más plazas de reasentamiento de refugiados, sin discriminación por raza, religión u origen.$es$),
  (324, 10, '{10.7}', $es$Protección de los menores en las zonas de acogida y durante la tramitación.$es$),
  (324, 16, '{16.2}', $es$Los menores no acompañados deben quedar protegidos frente al maltrato y la explotación.$es$);

-- Links of the catalogue that the review does not keep.
delete from public.commitment_sdgs s
using public.commitments c
where c.id = s.commitment_id
  and c.public_id like 'ESP-UPR4-050.%'
  and not exists (select 1 from sdg_review r where c.public_id = 'ESP-UPR4-050.' || r.n and r.goal = s.goal);

insert into public.commitment_sdgs (commitment_id, goal, targets, source, source_published_at, rationale, reviewed_at)
select c.id, r.goal, r.targets, 'hrct', null, r.rationale, date '2026-10-05'
from sdg_review r
  join public.commitments c on c.public_id = 'ESP-UPR4-050.' || r.n
on conflict (commitment_id, goal) do update set targets = excluded.targets, source = excluded.source, source_published_at = excluded.source_published_at, rationale = excluded.rationale, reviewed_at = excluded.reviewed_at;

drop table sdg_review;
